name: edart
description: Embedded Dart template engine and compiler. Compiles templates to Dart source code.
version: 0.1.8
homepage: https://github.com/mezoni/edart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  args: ^2.0.0
  build: ^2.0.0
  code_builder: ^3.7.0
  dart_style: ^2.0.0
  meta: ^1.3.0
  path: ^1.7.0
dev_dependencies:
  build_runner: ^1.12.2
  pedantic: ^1.11.0
  pubspec_parse: ^1.0.0
  test: ^1.16.8
